name: TicTicDesign
favicon: null
layout_spectrum: 1
typography_spectrum: 0.49563
title: TicTicDesign
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#212121'
    - '#6e6e6e'
    - '#999999'
    - '#ebebeb'
    - '#981a24'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
