name: TicTicDesign
favicon: null
layout_spectrum: 0.03379647224210203
typography_spectrum: 0.3829384851269424
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.372822776902467
  lightness: 0.6099577022250742
  saturation: 0.8086296312976629
  rhythmicContrast: 0.16130566084757447
purpose: []
