name: TicTicDesign
favicon: null
layout_spectrum: 0.25079
typography_spectrum: 0.4704
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#212121'
    - '#6e6e6e'
    - '#999999'
    - '#ebebeb'
    - '#981a24'
  brandStrength: 0.372822776902467
  lightness: 0.875
  saturation: 0.875
  rhythmicContrast: 1
purpose: []
